config/routes.rb
Rails.application.routes.draw do

  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/show'
  resources :restaurants do

    resources :reviews, only: [:new, :create]
    end

  resources :reviews, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5], message: "rating is not between 0-5" }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    redirect_to restaurants_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= simple_form_for (@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.submit "Edit Restaurant", class: "btn btn-primary" %>
<% end %>

<br>
<%= link_to "Back to Restaurants", restaurants_path, class: "btn btn-info" %></p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<h3><%= link_to "Create Restaurant", new_restaurant_path, class: "btn btn-primary" %></h3>


<% @restaurants.each do |restaurant| %>

  <h3>  <%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
  <p> <%= restaurant.category.capitalize %> </p>
  <p> <%= restaurant.address %> </p>
  <p> <%= restaurant.phone_number %> </p>
  <p> <em><%= restaurant.reviews.sample&.content %></em></p>

<% end %>

app/views/restaurants/new.html.erb
<h1>Add a New Restaurant</h1>

<%= simple_form_for (@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.submit "Add a Restaurant", class: "btn btn-primary" %>
<% end %>

<br>
<%= link_to "Back to Restaurants", restaurants_path, class: "btn btn-info" %></p>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<h3>Categorty</h3>
<p><%= @restaurant.category.capitalize %></p>

<h3>Address</h3>
<p><%= @restaurant.address %></p>

<h3>Phone Number</h3>
<p><%= @restaurant.phone_number %></p>

<h2>Reviews</h2>

<% @restaurant.reviews.each do |review| %>
  <div class="card">
    <p><%= review.content %></p>
    <p><%= review.rating %></p>
    <p><% review.rating.times do %>
      <i class="fas fa-star"></i>
    <% end %>
    <% (5 - review.rating).times do %>
      <i class="far fa-star"></i>
    <% end %></p>
  </div>
<% end %>

<br>

<p><%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant), class: "btn btn-primary" %>
<%= link_to "Delete", restaurant_path(@restaurant), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>

<%= link_to "Back to Restaurants", restaurants_path, class: "btn btn-info" %></p>

<p><%= link_to "Create Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %></p>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>New Review for <%= @restaurant.name %></h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: ["0", "1", "2", "3", "4", "5"] %>
  <%= f.submit "Submit Review", class: "btn btn-primary" %>
<% end %>

<br>

<%= link_to "Back to Restaurant", restaurant_path(@restaurant), class: "btn btn-info" %></p>

app/views/reviews/show.html.erb
<h1>Reviews for <%= @review.restaurant.name %></h1>

<% @reviews.each do |review| %>
  <p><%= review.content %></p>
  <p>Rating: <%= review.rating %></p>
<% end %>